### ISSUE TITLE
Intermittent RSpec failure with rack handler specs

### ISSUE THREAD

**Issue by rtyler** [openzipkin/zipkin-tracer#3]
I've not isolated this yet, but I'm sure it's a timing issue 

```
➜  zipkin-tracer git:(unreliable-specs) ✗ be rake spec
/home/tyler/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/lib:/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-support-3.0.4/lib -S /home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/exe/rspec ./spec/rack_handler_spec.rb
........

Finished in 0.01552 seconds (files took 0.11713 seconds to load)
8 examples, 0 failures

Randomized with seed 46989

➜  zipkin-tracer git:(unreliable-specs) ✗ be rake spec
/home/tyler/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/lib:/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-support-3.0.4/lib -S /home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/exe/rspec ./spec/rack_handler_spec.rb
....F...

Failures:

  1) ZipkinTracer::RackHandler configured without plugins with sample rate set to 0 does not sample a request
     Failure/Error: expect(trace_id.sampled?).to be_falsy
       expected: falsey value
            got: true
     # ./spec/rack_handler_spec.rb:45:in `block (5 levels) in <top (required)>'
     # ./lib/zipkin-tracer.rb:88:in `block in tracing_filter'
     # ./lib/zipkin-tracer.rb:87:in `synchronize'
     # ./lib/zipkin-tracer.rb:87:in `tracing_filter'
     # ./lib/zipkin-tracer.rb:70:in `call'
     # ./spec/rack_handler_spec.rb:47:in `block (4 levels) in <top (required)>'

Finished in 0.01555 seconds (files took 0.12222 seconds to load)
8 examples, 1 failure

Failed examples:

rspec ./spec/rack_handler_spec.rb:43 # ZipkinTracer::RackHandler configured without plugins with sample rate set to 0 does not sample a request

Randomized with seed 50368

/home/tyler/.rvm/rubies/ruby-2.1.5/bin/ruby -I/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/lib:/home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-support-3.0.4/lib -S /home/tyler/.rvm/gems/ruby-2.1.5@rubygems/gems/rspec-core-3.0.4/exe/rspec ./spec/rack_handler_spec.rb failed
➜  zipkin-tracer git:(unreliable-specs) ✗ 
```

**Comment by rtyler** [comment]
@jamescway in your work with the zipkin-tracer gem have you seen this issue? I don't want to mash around and try to fix it just yet given my unfamiliarity with the codebase

**Comment by jamescway** [comment]
@rtyler This might be causing non-determinism...  :hankey:  [here](https://github.com/twitter/finagle/blob/develop/finagle-thrift/src/main/ruby/lib/finagle-thrift/trace.rb#L135):hankey:  
```ruby
def should_sample?
    rand < (@sample_rate || DEFAULT_SAMPLE_RATE)
end
```
